version: '3.8'

services:
  murojaat_bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: murojaat_bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///murojaat_bot.db}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ADMIN_ID=${ADMIN_ID:-7474628933}
    volumes:
      - ./logs:/app/logs
      - ./murojaat_bot.db:/app/murojaat_bot.db
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"